const SHOW_RIGISTER = "SHOW_RIGISTER"
const HIDE_RIGISTER = "HIDE_RIGISTER"
const SHOW_LOGIN = "SHOW_LOGIN"
const HIDE_LOGIN = "HIDE_LOGIN"
const SHOW_INDEX = "SHOW_INDEX"
const HIDE_INDEX = 'HIDE_INDEX'
const SHOW_CUSLIST = 'SHOW_CUSLIST'
const HIDE_CUSLIST = 'HIDE_CUSLIST'
const GET_CUSLIST = 'GET_CUSLIST'
const SHOW_CUSINFO = 'SHOW_CUSINFO'
const HIDE_CUSINFO = 'HIDE_CUSINFO'
const SHOW_PLACEINFO = 'SHOW_PLACEINFO'
const HIDE_PLACEINFO = 'HIDE_PLACEINFO'
const SET_USERDATA = 'SET_USERDATA'
const SET_USERSTATUS = 'SET_USERSTATUS'
const SHOW_PERSONAL = 'SHOW_PERSONAL'
const HIDE_PERSONAL = 'HIDE_PERSONAL'
const SHOW_DISCOUNT = 'SHOW_DISCOUNT'
const HIDE_DISCOUNT = 'HIDE_DISCOUNT'
const GET_DISCOUNTLIST = 'GET_DISCOUNTLIST'
const SHOW_DISCOUNTSUB = 'SHOW_DISCOUNTSUB'
const HIDE_DISCOUNTSUB = 'HIDE_DISCOUNTSUB'
const SET_DISCOUNTSUBLIST = 'SET_DISCOUNTSUBLIST'
const SET_DISCOUNTSUM = 'SET_DISCOUNTSUM'
const SET_CUSFORMDATA = 'SET_CUSFORMDATA'
const SHOW_INVOICE = 'SHOW_INVOICE'
const HIDE_INVOICE = 'HIDE_INVOICE'
const GET_INVOICE = 'GET_INVOICE'
const SET_PLACEINFO = 'SET_PLACEINFO'

export default{
	SHOW_RIGISTER,
	HIDE_RIGISTER,
	SHOW_LOGIN,
	HIDE_LOGIN,
	SHOW_INDEX,
	HIDE_INDEX,
	SHOW_CUSLIST,
	HIDE_CUSLIST,
	GET_CUSLIST,
	SHOW_CUSINFO,
	HIDE_CUSINFO,
	SHOW_PLACEINFO,
	HIDE_PLACEINFO,
	SET_USERDATA,
	SET_USERSTATUS,
	SHOW_PERSONAL,
	HIDE_PERSONAL,
	SHOW_DISCOUNT,
	HIDE_DISCOUNT,
	GET_DISCOUNTLIST,
	SHOW_DISCOUNTSUB,
	HIDE_DISCOUNTSUB,
	SET_DISCOUNTSUBLIST,
	SET_DISCOUNTSUM,
	SET_CUSFORMDATA,
	SHOW_INVOICE,
	HIDE_INVOICE,
	GET_INVOICE,
	SET_PLACEINFO,
}
