const SHOW_RIGISTER = "SHOW_RIGISTER"
const HIDE_RIGISTER = "HIDE_RIGISTER"
const SHOW_LOGIN = "SHOW_LOGIN"
const HIDE_LOGIN = "HIDE_LOGIN"

export default{
	SHOW_RIGISTER,
	HIDE_RIGISTER,
	SHOW_LOGIN,
	HIDE_LOGIN,
}
