const SHOW_RIGISTER = "SHOW_RIGISTER"
const HIDE_RIGISTER = "HIDE_RIGISTER"
const SHOW_LOGIN = "SHOW_LOGIN"
const HIDE_LOGIN = "HIDE_LOGIN"
const SHOW_INDEX = "SHOW_INDEX"
const HIDE_INDEX = 'HIDE_INDEX'

export default{
	SHOW_RIGISTER,
	HIDE_RIGISTER,
	SHOW_LOGIN,
	HIDE_LOGIN,
	SHOW_INDEX,
	HIDE_INDEX,
}
